# Generated by Django 4.2.11 on 2024-05-08 02:37

import core.utils.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.CharField(default=core.utils.models.generate_uuid, editable=False, max_length=120, primary_key=True, serialize=False, unique=True),
        ),
    ]
