# Generated by Django 4.2.11 on 2024-05-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'base_manager_name': 'prefetch_manager', 'ordering': ['title', 'created_at']},
        ),
        migrations.AddField(
            model_name='tags',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
