# Generated by Django 4.2.11 on 2024-05-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_remove_product_tags_alter_productreview_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
