# Generated by Django 4.2.11 on 2024-06-03 15:50

import auto_prefetch
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0004_productitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='item',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product_item',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.productitem', verbose_name='Product items'),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='user',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_orders', to=settings.AUTH_USER_MODEL, verbose_name='User Order'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='order',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.cartorder', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='cartorderitems',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='oldprice',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=100, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
