# Generated by Django 4.2.11 on 2024-06-06 12:13

import auto_prefetch
import core.utils.media
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_cartorderitems_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product_item',
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product',
            field=auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='unique_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='resource',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.media.MediaHelper.get_file_upload_path),
        ),
        migrations.AddField(
            model_name='product',
            name='unique_keys',
            field=models.JSONField(default=list, help_text='List of unique keys for the product'),
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
