# Generated by Django 4.2.11 on 2024-06-07 18:46

import auto_prefetch
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecommerce', '0006_remove_cartorderitems_product_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default='', max_digits=100)),
                ('reference', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('status', models.CharField(blank=True, default='pending', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('order', auto_prefetch.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='ecommerce.cartorder')),
                ('user', auto_prefetch.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
