# Generated by Django 4.2.11 on 2024-05-27 11:51

import auto_prefetch
import core.utils.media
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_productimages_title'),
        ('blog', '0002_blogcategory_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=50)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to=core.utils.media.MediaHelper.get_image_upload_path)),
                ('sub_title', models.CharField(default='', max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('oldprice', models.DecimalField(decimal_places=2, max_digits=100)),
                ('category', auto_prefetch.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.category', verbose_name='Banner category')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'prefetch_manager',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('prefetch_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
