# Generated by Django 4.2.11 on 2024-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='sub_title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
