# Generated by Django 4.2.11 on 2024-05-31 03:25

import auto_prefetch
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer'),
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=auto_prefetch.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='users.customersupportrepresentative'),
        ),
    ]
